In [1]:
import numpy as np

In [2]:
a= np.array([[10,20,14,12],
            [4,5,8,45]])

### Shape => (Rows, Columns)

In [3]:
a.shape

(2, 4)

### Size = Elements count (Row X Column)

In [4]:
a.size

8

### ndim=> No of Dimension

In [10]:
a.ndim

2

In [11]:
a

array([[10, 20, 14, 12],
       [ 4,  5,  8, 45]])

### Get / Set Element
a[row, Column]

In [7]:
a[1,2]

8

In [8]:
a[1] # address of row index and shows all elements which has avaliable.

array([ 4,  5,  8, 45])

In [9]:
a[0]

array([10, 20, 14, 12])

In [15]:
### overwrite the value on specific locations on matrix
a[1,2] = -32

In [16]:
a

array([[ 10,  20,  14,  12],
       [  4,   5, -32,  45]])

In [17]:
a[0,0]= -8

In [18]:
a

array([[ -8,  20,  14,  12],
       [  4,   5, -32,  45]])

# Create Array

In [2]:
m= np.arange(25).reshape(5,5)

<IPython.core.display.Javascript object>

In [3]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
m.size

25

In [5]:
m.shape

(5, 5)

In [6]:
m.ndim

2

In [7]:
m[2::2, 3::]

array([[13, 14],
       [23, 24]])

In [9]:
m[4,4]

24

In [10]:
m[:, ::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
m[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])