# Numpy Array Slicing and Indexing

In [1]:
import numpy as np

In [2]:
a = np.array([[5.3,6.2,9.1,8.7,7.1],[5.2,6.2,4.8,9.5,7.3]])

In [3]:
a

array([[5.3, 6.2, 9.1, 8.7, 7.1],
       [5.2, 6.2, 4.8, 9.5, 7.3]])

In [4]:
b= np.array([[5.2,3.6,2.9,5.6,4.9],[8.3,8.56,6.93,8.165,5.63]])

In [5]:
b

array([[5.2  , 3.6  , 2.9  , 5.6  , 4.9  ],
       [8.3  , 8.56 , 6.93 , 8.165, 5.63 ]])

In [6]:
c= a+b

In [7]:
c

array([[10.5  ,  9.8  , 12.   , 14.3  , 12.   ],
       [13.5  , 14.76 , 11.73 , 17.665, 12.93 ]])

In [8]:
c.size

10

In [9]:
c.ndim

2

In [10]:
c.shape

(2, 5)

In [11]:
c-b

array([[5.3, 6.2, 9.1, 8.7, 7.1],
       [5.2, 6.2, 4.8, 9.5, 7.3]])

In [12]:
c-a

array([[5.2  , 3.6  , 2.9  , 5.6  , 4.9  ],
       [8.3  , 8.56 , 6.93 , 8.165, 5.63 ]])

# Slice
Slicing is similar to indexing but returns a sequence of items instead of a single item.

### There are two variants of the slicing syntax.
1. sequence[start (lower index)   :stop(Upper Index)] 
2. sequence[start:stop:step]. 

In [20]:
s= np.array([10,20,15,4,14,8,7,58,40,12])

In [21]:
s

array([10, 20, 15,  4, 14,  8,  7, 58, 40, 12])

In [23]:
# Negative indices work also
s[-9:-3]

array([20, 15,  4, 14,  8,  7])

In [25]:
s[-4:]

array([ 7, 58, 40, 12])

In [26]:
s[1:-3]

array([20, 15,  4, 14,  8,  7])

In [27]:
s[5:-2]

array([ 8,  7, 58])

In [28]:
s[5:9]

array([ 8,  7, 58, 40])

In [29]:
s[5:8]

array([ 8,  7, 58])

# Omitting Indices

### Omitting boundries are assumedto be the beginning (or end) of the list.

In [30]:
s[2:]

array([15,  4, 14,  8,  7, 58, 40, 12])

In [31]:
s[:-5]

array([10, 20, 15,  4, 14])

In [32]:
s[:9]

array([10, 20, 15,  4, 14,  8,  7, 58, 40])

In [33]:
s[-5:]

array([ 8,  7, 58, 40, 12])

In [34]:
# Every other Elements
s[::2]

array([10, 15, 14,  7, 40])

In [35]:
s

array([10, 20, 15,  4, 14,  8,  7, 58, 40, 12])

In [36]:
s[::3]

array([10,  4,  7, 12])

In [37]:
s[::4]

array([10, 14, 40])

## Array slicing

In [49]:
f= np.array([[4.5,5.2,8.9,5.6,3.9],[7.9,8.1,9.1,6.2,5.9],[8.95,5.96,4.96,1.36,7.96],[23.2,56.2,89.21,45.25,7.9],
             [56.23,8.21,7.14,8.19,9.325],[1.01,5.05,8.09,9.08,0.23]])

In [50]:
f

array([[ 4.5  ,  5.2  ,  8.9  ,  5.6  ,  3.9  ],
       [ 7.9  ,  8.1  ,  9.1  ,  6.2  ,  5.9  ],
       [ 8.95 ,  5.96 ,  4.96 ,  1.36 ,  7.96 ],
       [23.2  , 56.2  , 89.21 , 45.25 ,  7.9  ],
       [56.23 ,  8.21 ,  7.14 ,  8.19 ,  9.325],
       [ 1.01 ,  5.05 ,  8.09 ,  9.08 ,  0.23 ]])

# Slicing Work Much like Standard python slicing

In [51]:
f[0, 3:5]

array([5.6, 3.9])

In [52]:
f[1,3:5]

array([6.2, 5.9])

In [54]:
f[-1, 3:5]

array([9.08, 0.23])

In [55]:
f[-1,3:-1]

array([9.08])

In [56]:
f[-1,3:4]

array([9.08])

In [57]:
f[:4,:4]

array([[ 4.5 ,  5.2 ,  8.9 ,  5.6 ],
       [ 7.9 ,  8.1 ,  9.1 ,  6.2 ],
       [ 8.95,  5.96,  4.96,  1.36],
       [23.2 , 56.2 , 89.21, 45.25]])

In [58]:
f[4:,4:]

array([[9.325],
       [0.23 ]])

In [59]:
f

array([[ 4.5  ,  5.2  ,  8.9  ,  5.6  ,  3.9  ],
       [ 7.9  ,  8.1  ,  9.1  ,  6.2  ,  5.9  ],
       [ 8.95 ,  5.96 ,  4.96 ,  1.36 ,  7.96 ],
       [23.2  , 56.2  , 89.21 , 45.25 ,  7.9  ],
       [56.23 ,  8.21 ,  7.14 ,  8.19 ,  9.325],
       [ 1.01 ,  5.05 ,  8.09 ,  9.08 ,  0.23 ]])

In [60]:
f[4:, 3:]

array([[8.19 , 9.325],
       [9.08 , 0.23 ]])

## Strided are also possible

In [63]:
f[2::2,::2 ]

array([[ 8.95 ,  4.96 ,  7.96 ],
       [56.23 ,  7.14 ,  9.325]])

In [64]:
f.shape

(6, 5)

In [65]:
f.size

30

In [66]:
f.ndim

2

# Slices are References

### Slices are references to locations in memory

## These memory locations can be used in assignment operations


In [67]:
w= np.array([10,8,7,-6,5,-3])

In [68]:
w

array([10,  8,  7, -6,  5, -3])

In [69]:
w[-2:]

array([ 5, -3])

In [70]:
# We can insert an iterable of length two
w[-2:]= [-1,-2]

In [71]:
w

array([10,  8,  7, -6, -1, -2])

In [72]:
# or a scaler Value
w[-2:]= 93
w

array([10,  8,  7, -6, 93, 93])

In [73]:
cf= np.array.__call__([1,5,6])

In [74]:
cf

array([1, 5, 6])

In [ ]:
# Dunder methods , Special methods, python data model
#Fluent python