In [1]:
import numpy as np

In [3]:
p = np.array([5,10,58,23])

In [6]:
type(p)

<attribute 'dtype' of 'numpy.ndarray' objects>

In [7]:
p.dtype

dtype('int32')

In [8]:
s = np.array([4.5,5.6,8.9,8.2])

In [9]:
type(s)

numpy.ndarray

In [10]:
s.dtype

dtype('float64')

In [11]:
p

array([ 5, 10, 58, 23])

In [12]:
s

array([4.5, 5.6, 8.9, 8.2])

In [43]:
p[0]= 45

In [44]:
p[3]

23

In [45]:
s[3]

8.2

In [46]:
p

array([45, 10, 58, 23])

# Properties of NumPy
1. Dimession
2. Shape
3. Size

In [19]:
s.ndim

1

In [20]:
s.shape

(4,)

In [38]:
s.size

4

In [21]:
p.ndim

1

In [22]:
p.shape

(4,)

In [39]:
p.size

4

# Opertainos on array

In [28]:
y= s+p
y

array([ 9.5, 15.6, 66.9, 31.2])

In [25]:
y

array([ 9.5, 15.6, 66.9, 31.2])

In [29]:
x= s-p
x

array([ -0.5,  -4.4, -49.1, -14.8])

In [30]:
z= s/p
z

array([0.9       , 0.56      , 0.15344828, 0.35652174])

In [32]:
h= s**p
h

array([1.84528125e+03, 3.03305489e+07, 1.16043384e+55, 1.04164229e+21])

In [33]:
np.sin(p)

array([-0.95892427, -0.54402111,  0.99287265, -0.8462204 ])

In [34]:
np.cos(s)

array([-0.2107958 ,  0.77556588, -0.86543521, -0.33915486])

In [36]:
np.tan(s)

array([ 4.63733205, -0.81394328, -0.57892359, -2.7737493 ])

In [41]:
np.sqrt(s)

array([2.12132034, 2.36643191, 2.98328678, 2.86356421])

In [42]:
np.sqrt(p)

array([2.23606798, 3.16227766, 7.61577311, 4.79583152])